
//  User Action Types
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const VERIFACATION_SUCCESS = 'VERIFACATION_SUCCESS';
export const VERIFACATION_FAILED = 'VERIFACATION_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_FAILD';
export const LOGOUT_USER = 'LOGOUTUSER';
export const CHECK_USER = 'CHECK_USER'
export const CHECK_ROLE = 'CHECK_ROLE'


// Product Action Types
export const UPLOAD_PRODUCT_SUCCESS = "UPLOAD_PRODUCT_SUCCESS";
export const UPLOAD_PRODUCT_FAILED = "UPLOAD_PRODUCT_FAILED";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILED = "GET_ALL_PRODUCTS_FAILED";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILED = "GET_ALL_CATEGORIES_FAILED";


export const GET_FILTERED_PRODUCT_SUCCESS = "GET_FILTERED_PRODUCT_SUCCESS";
export const GET_FILTERED_PRODUCT_FAILED = "GET_FILTERED_PRODUCT_FAILED";
export const GET_ORDER_BY_PRICE_SUCCESS = "GET_ORDER_BY_PRICE_SUCCESS";
export const GET_ORDER_BY_PRICE_FAILED = "GET_ORDER_BY_PRICE_FAILED";


// Cart Action Types
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//Order Action Types
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS';
export const GET_ALL_ORDERS_FAILED = 'GET_ALL_ORDERS_FAILED';
